name: Generate Rainbow Contribution Graph

on:
  workflow_dispatch: # Permite rodar manualmente
  schedule:
    - cron: "0 0 * * *" # Executa diariamente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_habits: yes
          plugin_habits_trim: true
          plugin_habits_charts: true
          plugin_habits_charts_type: calendar
          plugin_habits_languages_limit: 8
