name: Generate Contribution Calendar

on:
  workflow_dispatch: # Permite rodar manualmente
  schedule:
    - cron: "0 0 * * *" # Executa diariamente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_isocalendar_colors: "gradient|pink,lavender,lightblue,peach,lightgreen"
          plugin_isocalendar_output: "github-metrics.svg"  # Nome do arquivo gerado
          plugin_isocalendar_skip: "false" # Garantir que o calendário seja gerado sem descrição
