name: Generate Rainbow Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_contributions_graph: yes
          plugin_contributions_graph_colors: rainbow
